In [1]:
import numpy as np
list1 = [1, 2, 3]
vector1 = np.array(list1)
print(vector1)

vector2 = np.arange(1, 4, 2)
print(vector2)

[1 2 3]
[1 3]


In [15]:
u = np.array([1, 2, 3, 4])
v = np.array([5, 6, 7, 8])

print(u + v)

[ 6  8 10 12]


In [21]:
print(np.add(u, v))

u = np.array([1, 2, 3, 4])
v = np.array([5])
print(u + v)

[6 7 8 9]
[6 7 8 9]


In [29]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
print(u * v)
print(v % u)
print(v // u)

[ 4 10 18]
[0 1 0]
[4 2 2]


In [28]:
u = np.array([1, 5, 6, 10])
print(np.linalg.norm(u))

12.727922061357855


In [33]:
u = np.array([1, 2])

v = np.array([2, 3])
print(np.multiply(u, v))

print(u.dot(v))
print(np.dot(u, v))
print(np.dot(v, u))

[2 6]
8
8
8


In [49]:
matrix1 = np.array([[1, 2], [3, 4]])
print(matrix1)

shape = (2, 3)
matrix2 = np.random.randint(2, 4, shape)
print(matrix2)

[[1 2]
 [3 4]]
[[2 2 3]
 [3 2 3]]


In [ ]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A.T)

[[1 3 5]
 [2 4 6]]


In [56]:
A = np.array([
    [1, 2],
    [3, 4]
])
print(np.linalg.det(A))

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(np.linalg.det(B))

-2.0000000000000004
-9.51619735392994e-16


In [57]:
A = np.array([
    [1, 2],
    [3, 1]
])
print(np.linalg.det(A))

print(np.linalg.inv(A))

-5.000000000000001
[[-0.2  0.4]
 [ 0.6 -0.2]]


In [60]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
element = np.transpose(A)
print(element[:-1])

[[1 3 5]]


In [62]:
A = np.array([
    [6, 10], [10, 6], [10, 10]
])
data = A.flatten()
result = np.argmax(data)
print(result) #Return the first index

1


In [63]:
data = np.array([
    [2, 5, 8], [3, 4, 1]
])
print(data)
e_data = np.power(np.e, data)
print(e_data)
print(np.argmin(e_data, axis = 1))

[[2 5 8]
 [3 4 1]]
[[7.38905610e+00 1.48413159e+02 2.98095799e+03]
 [2.00855369e+01 5.45981500e+01 2.71828183e+00]]
[0 2]


In [68]:
#Cosine Similarity

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

cosine = (np.dot(x, y)) / ((np.linalg.norm(x)) * (np.linalg.norm(y)))
print(cosine)

0.9746318461970762


In [18]:
#Image Similarity
import numpy as np
from PIL import Image
image1 = Image.open('data/image1.jpg')
image2 = Image.open('data/image2.jpg')
query_image = Image.open('data/query_image.jpg')

print("Size:")
print(image1.size)
print(image2.size)
print(query_image.size)

img1_data = np.array(image1)
img2_data = np.array(image2)
query_img_data = np.array(query_image)

print("Shape: ")
print(img1_data.shape)
print(img2_data.shape)
print(query_img_data.shape)

Size:
(320, 256)
(320, 256)
(320, 256)
Shape: 
(256, 320, 3)
(256, 320, 3)
(256, 320, 3)


In [20]:
def compute_average(vector):
    return vector.mean()
img1_gray = np.apply_along_axis(compute_average, axis = 2, arr = img1_data)
img2_gray = np.apply_along_axis(compute_average, axis = 2, arr = img2_data)
query_img_gray = np.apply_along_axis(compute_average, axis = 2, arr = query_img_data)

img1_flatten = img1_gray.flatten()
img2_flatten = img2_gray.flatten()
query_img_flatten = query_img_gray.flatten()


In [22]:
def compute_cosine_similarity(A, B):
    cosine = np.dot(A, B) / ((np.linalg.norm(A)) * (np.linalg.norm(B)))
    return cosine
cosine1 = compute_cosine_similarity(img1_flatten, query_img_flatten)
print("cosine1: ", cosine1)

consine2 = compute_cosine_similarity(img2_flatten, query_img_flatten)
print("cosine2: ", consine2)

cosine1:  0.9388644256771876
cosine2:  0.8300677529901603
