In [117]:
import numpy as np

def create_train_data():
    data = [
        ['Sunny', 'Hot', 'High', 'Weak', 'no'],
        ['Sunny', 'Hot', 'High', 'Strong', 'no'],
        ['Overcast', 'Hot', 'High', 'Weak', 'yes'],
        ['Rain', 'Mild', 'High', 'Weak', 'yes'],
        ['Rain', 'Cool', 'Normal', 'Weak', 'yes'],
        ['Rain', 'Cool', 'Normal', 'Strong', 'no'],
        ['Overcast', 'Cool', 'Normal', 'Strong', 'yes'],
        ['Overcast', 'Mild', 'High', 'Weak', 'no'],
        ['Sunny', 'Cool', 'Normal', 'Weak', 'yes'],
        ['Rain', 'Mild', 'Normal', 'Weak', 'yes']
    ]
    return np.array(data)
train_data = create_train_data()

In [118]:
def compute_prior_probability(train_data):
    Y_unique = ['no', 'yes']
    prior_probability = np.zeros(len(Y_unique))
    for i in range(len(Y_unique)):
        prior_probability[i] = len(np.where(train_data[:, 4] == Y_unique[i])[0]) / len(train_data)
    return prior_probability

prior_probability = compute_prior_probability(train_data = train_data)
print(prior_probability)

[0.4 0.6]


In [130]:
def compute_conditional_probability(train_data):
    y_unique = ['no', 'yes']
    conditional_probability = []
    list_x_name = []
    for i in range(train_data.shape[1] - 1):
        x_unique = np.unique(train_data[:, i])
        list_x_name.append(x_unique)
        print(x_unique)
        x_conditional_probability = np.zeros((len(y_unique), len(x_unique)))
        for j in range(len(y_unique)):
            for k in range(len(x_unique)):
                condition_x = train_data[:, i] == x_unique[k]
                condition_y = train_data[:, 4] == y_unique[j]
                x_conditional_probability[j, k] = len(np.where(condition_x & condition_y)[0]) / len(np.where(train_data[:, 4] == y_unique[j])[0])
        conditional_probability.append(x_conditional_probability)
    return conditional_probability, list_x_name

conditional_probability, list_x_name = compute_conditional_probability(train_data)
print(conditional_probability, list_x_name)

['Overcast' 'Rain' 'Sunny']
['Cool' 'Hot' 'Mild']
['High' 'Normal']
['Strong' 'Weak']
[array([[0.25      , 0.25      , 0.5       ],
       [0.33333333, 0.5       , 0.16666667]]), array([[0.25      , 0.5       , 0.25      ],
       [0.5       , 0.16666667, 0.33333333]]), array([[0.75      , 0.25      ],
       [0.33333333, 0.66666667]]), array([[0.5       , 0.5       ],
       [0.16666667, 0.83333333]])] [array(['Overcast', 'Rain', 'Sunny'], dtype='<U8'), array(['Cool', 'Hot', 'Mild'], dtype='<U8'), array(['High', 'Normal'], dtype='<U8'), array(['Strong', 'Weak'], dtype='<U8')]


In [120]:
def train_naive_bayes(train_data):
    #1. Xac suat tien nghiem
    prior_probability = compute_prior_probability(train_data)

    #2. Conditional
    conditional_probability, list_x_name = compute_conditional_probability(train_data)
    return prior_probability, conditional_probability, list_x_name

train_naive_bayes(train_data)

['Overcast' 'Rain' 'Sunny']
['Cool' 'Hot' 'Mild']
['High' 'Normal']
['Strong' 'Weak']


(array([0.4, 0.6]),
 [array([[0.25      , 0.25      , 0.5       ],
         [0.33333333, 0.5       , 0.16666667]]),
  array([[0.25      , 0.5       , 0.25      ],
         [0.5       , 0.16666667, 0.33333333]]),
  array([[0.75      , 0.25      ],
         [0.33333333, 0.66666667]]),
  array([[0.5       , 0.5       ],
         [0.16666667, 0.83333333]])],
 [array(['Overcast', 'Rain', 'Sunny'], dtype='<U8'),
  array(['Cool', 'Hot', 'Mild'], dtype='<U8'),
  array(['High', 'Normal'], dtype='<U8'),
  array(['Strong', 'Weak'], dtype='<U8')])

In [121]:
def get_index(feature_name, list_features):
    return np.where(list_features == feature_name)[0][0]

print(list_x_name[0])
print(get_index('Sunny', list_x_name[0]))

['Overcast' 'Rain' 'Sunny']
2


In [127]:
index = get_index('Sunny', list_x_name[0])
print(conditional_probability[0][1][index])

0.16666666666666666


In [140]:
X = ['Sunny', 'Cool', 'High', 'Strong']
def predict(X, list_x_name, prior_probability, conditional_probability):
    x1 = get_index(X[0], list_x_name[0])
    x2 = get_index(X[1], list_x_name[1])
    x3 = get_index(X[2], list_x_name[2])
    x4 = get_index(X[3], list_x_name[3])

    p0 = prior_probability[0] * conditional_probability[0][0, x1] * conditional_probability[1][0, x2] * conditional_probability[2][0, x3] * conditional_probability[3][0, x4]
    p1 = prior_probability[1] * conditional_probability[0][1, x1] * conditional_probability[1][1, x2] * conditional_probability[2][1, x3] * conditional_probability[3][1, x4]
    if p0 > p1:
        y_pred = 'no', p0
    else:
        y_pred = 'yes', p1
    return y_pred

result = predict(X, list_x_name, prior_probability, conditional_probability)
print(result)


('no', np.float64(0.018750000000000003))
