In [55]:
#List and Numpy Array
import numpy as np
n = 5
zeros_array_1d = np.zeros(n)
print(zeros_array_1d)

[0. 0. 0. 0. 0.]


In [93]:
data = np.array([6, 5, 7, 1, 3, 2])
print(data)


data = np.append(data, 5)
print(data)

data = np.insert(data, 2, 10)
print(data)

data = np.append(data, [11, 12])
print(data)

data[0] = 66
print(data)

data2 = [13, 14, 15]
data = np.append(data, data2)
print(data)

data = data * 3
print(data)
list_data = [1, 2, 3]
list_data = list_data * 3
print(list_data)

[6 5 7 1 3 2]
[6 5 7 1 3 2 5]
[ 6  5 10  7  1  3  2  5]
[ 6  5 10  7  1  3  2  5 11 12]
[66  5 10  7  1  3  2  5 11 12]
[66  5 10  7  1  3  2  5 11 12 13 14 15]
[198  15  30  21   3   9   6  15  33  36  39  42  45]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [94]:
data.sort()
print(data)
data = data[::-1]
print(data)


[  3   6   9  15  15  21  30  33  36  39  42  45 198]
[198  45  42  39  36  33  30  21  15  15   9   6   3]


In [86]:
data = np.delete(data, 2)
print(data)

deleted_index = np.where(data == 6)[0][0] # data cua minh, tra ve tupple
data = np.delete(data, deleted_index)
print(data)

[198  45  39  36  33  30  21  15  15   9   6   3]
[198  45  39  36  33  30  21  15  15   9   3]


In [99]:
del list_data[1:3]
print(list_data)

data = np.concatenate((data[:2], data[3:]))
print(data)


[1]
[198  45  30  21  15  15   9   6   3]


In [ ]:
data = np.delete(data, range(1, 3))
print(data)

2


In [116]:
a_data = np.array([6, 5, 7, 1, 9, 2, 7])
count = (a_data == 7).sum()
print(count)

2


In [122]:
data = np.array([6, 5, 7, 1, 2, 9])

data_copy = data.copy()
print(type(data_copy))

print(np.min(data))

print(np.max(data))

print(np.shape(data))

<class 'numpy.ndarray'>
1
9
(6,)


In [125]:
print(data)
summation = np.sum(data)
print(summation)

[6 5 7 1 2 9]
30


In [ ]:
import numpy as np

#Example arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#Zip-like operation using numpy.dstack()
zipped_arr = np.dstack((arr1, arr2))[0] # => tupple
print(len(zipped_arr))
for i in range(len(arr1)):
    print(zipped_arr[i])

3
[1 4]
[2 5]
[3 6]


In [137]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 1
(1,) 2
(2,) 3


In [146]:
#Sum of even numbers
import numpy as np
arr = np.array(list(range(1, 11)))
even_numbers = arr[arr % 2 == 0]
print(arr % 2 == 0)
sum_even_numbers = np.sum(even_numbers)
print(arr)
print(even_numbers)
print(sum_even_numbers)


index = arr % 2 == 0
print(index)
print(arr[index])

[False  True False  True False  True False  True False  True]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
30
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [144]:
#Sum of elements with even indices
even_index_elements = arr[::2]
sum_even_indices = np.sum(even_index_elements)
print(arr)
print(even_index_elements)
print(sum_even_indices)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
25


In [152]:
a = np.array([1, 2, 3, 4, 5])
print(a[[1, 4]])
print(a[[1, 3, 4]])

[2 5]
[2 4 5]


In [151]:
print(a[a > 2])

[3 4 5]


In [161]:
#Reshaping: Change the shape of an array without changing its data
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.reshape(2, 3))


#Flattening: Convert a multi_dimensional array into a 1D array
arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())

#Concatenation: Joining two or more arrays
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))



[[1 2 3]
 [4 5 6]]
[1 2 3 4]
[1 2 3 4]


In [167]:
# Broadcasting and Vectorization in Numpy
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([1, 2])

# [
#     [1, 2],
#     [1, 2],
#     [1, 2]
# ]
result = a + b
print(result)
print("______________________________")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[[2 4]
 [4 6]
 [6 8]]
______________________________
[5 7 9]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
result = a * b

# nó sẽ hỗ trợ thực hiện nhân cùng lúc, ví dụ nhân 4 phần tử cùng lúc => nhanh hơn rất nhiều so với for
print(result)

[ 5 12 21 32]


In [184]:
#2D List & 2D Array
list_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(list_2d)

print("________________")
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(array_2d)


#Accessing elements in 2D list
print("Element at (1, 2) in list_2d: ", list_2d[1][2])

#Accessing elements in 2D Numpy Array
print("Element at (1, 2) in array_2d: ", array_2d[1, 2])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2) in list_2d:  6
Element at (1, 2) in array_2d:  6


In [205]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
result = np.dot(A, B)
print(result)

[[ 58  64]
 [139 154]]


In [ ]:
#Shape of Numpy Arrays
numbers = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
dim = numbers.ndim
print(dim)

print(numbers.shape)

numbers2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(numbers2.shape)
print(numbers2.ndim)

print(numbers2.reshape((2, 4), order = "C")) #C-like index order (default)
print(numbers2.reshape((2, 4), order = "F")) #Fortran-like index order

2
(2, 4)
(8,)
1
[[1 2 3 4]
 [5 6 7 8]]
[[1 3 5 7]
 [2 4 6 8]]


In [ ]:
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
filtered_elements = array[(array > 2) & (array < 5)]
filtered_elements = filtered_elements[::-1]
print(filtered_elements)

# [
#     [F, F, T],
#     [T, F, F],
#     [F, F, F]
# ]
# & thuc hien tren T va F
# => Python tra ve mang 1 chieu

[4 3]


In [217]:
original_array = np.arange(12)
original_array = original_array.reshape(3, 4)
print(original_array.shape)

(3, 4)


In [ ]:
print(np.array([1, 2, 3, 4,5 ]))
print(np.arange(1, 6))


print(np.array(1, 2, 3, 4, 5)) # (object, dtype)

print(np.array("Hello", str))

Hello


In [220]:
print(np.array([1, 2, 3]) + np.array([[1], [2], [3]])) 

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [225]:
def computeIoU(boxA, boxB):
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])
    interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)
    boxAArea = (boxA[2] - boxA[0] + 1) * (boxA[3] - boxA[1] + 1)
    boxBArea = (boxB[2] - boxB[0] + 1) * (boxB[3] - boxB[1] + 1)
    iou = interArea / float(boxAArea + boxBArea - interArea)
    return iou
boxA = [0, 0, 100, 100]
boxB = [50, 50, 150, 150]
print(computeIoU(boxA, boxB))

0.14611538677602381


In [252]:
import time
boxes = []
for i in range(10000):
    boxes.append([i + 1, i + 1, i + 1, i + 1])
initialTime = time.time()
for i in range(1, len(boxes)):
    iou = computeIoU(boxes[0], boxes[i])
print(time.time() - initialTime)

0.003889799118041992


In [253]:
initialTime = time.time()
boxes = np.array(boxes)
x1 = boxes[:,0]
y1 = boxes[:,1]
x2 = boxes[:,2]
y2 = boxes[:,3]
areas = (x2 - x1 + 1) * (y2 - y1 + 1)

xx1 = np.maximum(x1[0], x1[1:])
yy1 = np.maximum(y1[0], y1[1:])
xx2 = np.minimum(x2[0], x2[1:])
yy2 = np.minimum(y2[0], y2[1:])

w = np.maximum(xx2 - xx1 + 1, 0)
h = np.maximum(yy2 - yy1 + 1, 0)
inter = w * h
print(inter)
iou = inter / (areas[0] + areas[1:] - inter)
print(iou)
print(time.time() - initialTime)

[0 0 0 ... 0 0 0]
[0. 0. 0. ... 0. 0. 0.]
0.005474090576171875


In [261]:
#SIDM: single instruction, multiple data
def non_maximum_suppression(boxes, scores, iou_threshold):
    sorted_indices = sorted(range(len(scores)), key = lambda x : -scores[x])
    kept_indices = []
    while sorted_indices:
        index = sorted_indices.pop(0)
        kept_indices.append(index)
        selected_indices = []
        for i in sorted_indices:
            iou = computeIoU(boxes[index], boxes[i])
            if iou <= iou_threshold:
                selected_indices.append(i)
        sorted_indices = selected_indices
    return kept_indices

boxes = [
    [100, 100, 210, 210],
    [105, 105, 215, 215],
    [150, 150, 250, 250]
]
scores = [0.9, 0.8, 0.7]
print(non_maximum_suppression(boxes, scores, 0.7))

[0, 2]


In [273]:
def non_maximum_suppression_array(boxes, scores, threshold):
    if len(boxes) == 0:
        return []
    x1 = boxes[:,0]
    y1 = boxes[:,1]
    x2 = boxes[:,2]
    y2 = boxes[:,3]
    areas = (x2 - x1 + 1) * (y2 - y1 + 1)
    keep = []
    order = scores.argsort()[::-1]
    while order.size > 0:
        i = order[0]
        keep.append(i)
        xx1 = np.maximum(x1[i], x1[order[1:]])
        yy1 = np.maximum(y1[i], y1[order[1:]])
        xx2 = np.minimum(x2[i], x2[order[1:]])
        yy2 = np.minimum(y2[i], y2[order[1:]])
        w = np.maximum(0, xx2 - xx1 + 1)
        h = np.maximum(0, yy2 - yy1 + 1)
        intersection = w * h
        iou = intersection / (areas[i] + areas[order[1:]] - intersection)
        inds = np.where(iou <= threshold)[0]
        print(inds)
        order = order[inds + 1]
    return keep
boxes = np.array(boxes)
scores = np.array(scores)
threshold = 0.3
print(boxes[non_maximum_suppression_array(boxes, scores, threshold)])

[1]
[]
[[100 100 210 210]
 [150 150 250 250]]


In [271]:
arr = np.array([5, 1, 3, 7])
order = arr.argsort()[::-1]
print(arr[[0, 1, 2]])

[5 1 3]
