In [3]:
import numpy as np
list1D = [1, 2, 3]
data = np.array(list1D)
print(data)
print(data.shape)

list2D = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(list2D.shape)

data = np.array([[1, 2, 3], [1, 2, 3]])
print(data.shape)

[1 2 3]
(3,)
(2, 3)
(2, 3)


In [ ]:
def compute(n):
  return n ** 3
data = [1, 2, 3]
vectorize = np.vectorize(compute)
print(vectorize(np.array(data)))
print(np.array(data) ** 3)

[ 1  8 27]
[ 1  8 27]


In [ ]:
zeros_np = np.zeros((10, 10))
print(zeros_np)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
shape = (4, 5)
data = np.zeros(shape)
print(data)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
shape = (3, 5)
data = np.ones(shape)
print(data)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
data = np.full(shape, 999)
print(data)

[[999 999 999 999 999]
 [999 999 999 999 999]
 [999 999 999 999 999]]


In [ ]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#random from 0 to 1
random = np.random.random((2, 3))
print(random)

[[0.08493852 0.07443026 0.42014358]
 [0.02653949 0.71586892 0.24528642]]


In [ ]:
data = np.arange(0, 5, 0.5)
print(data)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
data = np.arange(10)
data = data.reshape(2, 5, 1)
print(data)
print("_________________________")
data = np.reshape(data, (2, 5))
print(data)

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]
_________________________
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#lay random from 1 to 4, exclusive: 5
data = np.random.randint(1, 5, (2, 3))
print("data: \n", data)


vector1 = data.flatten()
print(vector1)


reshape = data.reshape(-1)
print(reshape)

data: 
 [[1 2 1]
 [1 3 3]]
[1 2 1 1 3 3]
[1 2 1 1 3 3]


In [ ]:
data = np.arange(10).reshape(2, 5)
print(data)

data = np.reshape(data, (5, -1))
print(data)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#repeat(data, repeats, axis)

data = np.array([1, 4])
data = np.repeat(data, 2)
print(data)
print("\n\n")


data = np.arange(100).reshape(10, 10)
print(data)
print('\n\n')
#vertical: 0, horizontal: 1

data = np.repeat(data, 2, axis = 0)
print(data)
print('\n\n')
data = np.repeat(data, 2, axis = 1)
print(data)


[1 1 4 4]



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]



[[ 0  1  2  3  4  5  6  7  8  9]
 [ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]
 [90 91 92 93 94 95 96 97 

In [10]:
#Aray Indexing

#Slicing
data = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(data, end = "\n\n")
print(data[1:3], end = "\n\n")
print(data[0:1, 0], end = "\n\n")
print(data[:], end = "\n\n")

[[1 2]
 [3 4]
 [5 6]]

[[3 4]
 [5 6]]

[1]

[[1 2]
 [3 4]
 [5 6]]



In [22]:
data = np.arange(9).reshape(3, 3)
print(data, end = "\n\n")

sub_data = data[1, :]
print(sub_data, end = "\n\n")

sub_data[2] = 99

print(sub_data, end = '\n\n')

print("Data has been changed:\n", data)
#Nó tạo biến mới có view ít hơn, nhưng dùng chung vùng bộ nhớ => mọi thay đổi trên sub_data => đều làm thay đổi data

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[3 4 5]

[ 3  4 99]

Data has been changed:
 [[ 0  1  2]
 [ 3  4 99]
 [ 6  7  8]]


In [25]:
data_list = [1, 2, 3, 4, 5]
sub_list = data_list[2:]
print(sub_list)
sub_list[2] = 100
print(sub_list)
print(data_list)

[3, 4, 5]
[3, 4, 100]
[1, 2, 3, 4, 5]


In [29]:
data = np.arange(4).reshape(2, 2)
sub_data = data[:,:]
#Thực hiện phép gán, thay đổi giá trị của biến sub_data, tức là trỏ tới chỗ khác => data không thay đổi
sub_data = 20
print(data)

[[0 1]
 [2 3]]


In [31]:
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a = data[1, :]
print(a)
print(a.shape)

print('\n\n')

b = data[1:2, :]
print(b)
print(b.shape)

[4 5 6]
(3,)



[[4 5 6]]
(1, 3)


In [45]:
i1, j1 = 0, 0
print(data[i1][j1], end = '\n\n')

i2, j2 = 1, 2
print(data[i2][j2], end = '\n\n')

print(data[[i1, i2], [j1, j2]], end = '\n\n')

#print [4, 9]: (1, 0) va (2, 2)
print(data[[1, 2], [0, 2]], end = '\n\n')
#print [3, 5]: (0, 2) va (1, 1)
print(data[[0, 1], [2, 1]], end = '\n\n')
#print [1, 2, 3]
print(data[[0], [0, 1, 2]])

1

6

[1 6]

[4 9]

[3 5]

[1 2 3]


In [59]:
print(data, end = '\n\n')

bool_matrix =  data > 4

print(bool_matrix, end = '\n\n')

#result luon la vector
result = data[bool_matrix]
print(result, end = '\n\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[False False False]
 [False  True  True]
 [ True  True  True]]

[5 6 7 8 9]



In [69]:
data = np.arange(4).reshape(2, 2)
print(data, end = '\n\n')

print(np.sum(data, axis = 0), end = '\n\n')

print(np.sum(data, axis = 1), end = '\n\n')

print(np.mean(data), end = '\n\n')

print(np.mean(data, axis = 0), end = '\n\n')

print(np.mean(data, axis = 1), end = '\n\n')

print(np.max(data, axis = 0), end = '\n\n')

print(np.max(data, axis = 1), end = '\n\n')

[[0 1]
 [2 3]]

[2 4]

[1 5]

1.5

[1. 2.]

[0.5 2.5]

[2 3]

[1 3]



In [73]:
#Broadcasting
end = '\n\n'
data = np.arange(1, 4)
print(data, end = end)


print(data + 10, end = end)

print(data - 10, end = end)

[1 2 3]

[11 12 13]

[-9 -8 -7]



In [75]:
data = np.arange(1, 10).reshape(3, 3)
print(data, end = end)

b = np.array([1, 2, 3])
print(data + b, end = end)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]



In [85]:
data = np.array([1, 2, 3])

print(data, end = end)

max_value = data.max()
print(max_value, end = end)

data_exp = np.exp(data)
print(data_exp, end = end)

sum_data_exp = np.sum(data_exp)
print(sum_data_exp, end = end)

result = data_exp / sum_data_exp
print(result, end = end)

[1 2 3]

3

[ 2.71828183  7.3890561  20.08553692]

30.19287485057736

[0.09003057 0.24472847 0.66524096]

