In [152]:
#Uniform Distribution(Continuous)

import numpy as np
data = np.random.uniform(0, 1, (2, 3))
print(data)

[[0.38661429 0.86531084 0.00641966]
 [0.7586462  0.6595859  0.07346707]]


In [153]:
#Normal Distribution
data = np.random.normal(0, 1, (2, 3))
print(data)

[[-0.70950001  0.27934881  0.00828788]
 [-1.10030738 -0.93198939  1.10318745]]


In [154]:
import numpy as np

!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

zsh:1: command not found: gdown


In [155]:
import pandas as pd
data = pd.read_csv('advertising.csv')
print(data)

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]


In [156]:
import numpy as np
x = data['TV']
y = data['Sales']

In [157]:
correlation_coefficien = np.corrcoef(x, y)
print(correlation_coefficien)

[[1.         0.90120791]
 [0.90120791 1.        ]]


In [158]:
x = data['Radio']
y = data['Sales']
print(np.corrcoef(x, y))

[[1.        0.3496311]
 [0.3496311 1.       ]]


In [159]:
x = data['Newspaper']
y = data['Sales']
print(np.corrcoef(x, y))

[[1.         0.15796003]
 [0.15796003 1.        ]]


In [160]:
data_corr_coef = data.corr()
print(data_corr_coef)

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000


In [161]:
data.head(5)

,TV,Radio,Newspaper,Sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,12.0
3,151.5,41.3,58.5,16.5
4,180.8,10.8,58.4,17.9


In [162]:
data.tail(5)

,TV,Radio,Newspaper,Sales
195,38.2,3.7,13.8,7.6
196,94.2,4.9,8.1,14.0
197,177.0,9.3,6.4,14.8
198,283.6,42.0,66.2,25.5
199,232.1,8.6,8.7,18.4


In [163]:
data.describe()

,TV,Radio,Newspaper,Sales
count,200.000000,200.000000,200.000000,200.000000
mean,147.042500,23.264000,30.554000,15.130500
std,85.854236,14.846809,21.778621,5.283892
min,0.700000,0.000000,0.300000,1.600000
25%,74.375000,9.975000,12.750000,11.000000
50%,149.750000,22.900000,25.750000,16.000000
75%,218.825000,36.525000,45.100000,19.050000
max,296.400000,49.600000,114.000000,27.000000


In [164]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [165]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [166]:
data = pd.read_csv('vi_text_retrieval.csv')
print(data)

             id                                           question  \
0    1570446247  Quang Hải giành được chức vô địch U21 quốc gia...   
1    1570445661                   Mỗi hiệp bóng đá kéo dài bao lâu   
2    1570382095            Quân đội Hoa Kỳ gồm những lực lượng nào   
3    1570382072                                     Ngọc Lan là ai   
4    1570382037         Thu Phương từng được những giải thưởng nào   
..          ...                                                ...   
495  1569486091  Dân số của Sóc Trăng đứng thứ mấy trong khu vự...   
496  1569486072  Các nguyên lý toán học của triết học tự nhiên ...   
497  1569486003                    Biến đổi khí hậu Trái Đất là gì   
498  1569485614     Phanxicô Xaviê Trương Bửu Diệp mất vào năm nào   
499  1569485573  Mật độ dân số của vùng trung du và miền núi ph...   

                                                  text  
0    Năm 2013 , Nguyễn Quang Hải giành chức vô địch...  
1    Một trận đấu bóng đá thông thường có hai

In [167]:
data.iloc[0]

id                                                 1570446247
question    Quang Hải giành được chức vô địch U21 quốc gia...
text        Năm 2013 , Nguyễn Quang Hải giành chức vô địch...
Name: 0, dtype: object

In [168]:
data['text']

0      Năm 2013 , Nguyễn Quang Hải giành chức vô địch...
1      Một trận đấu bóng đá thông thường có hai hiệp ...
2      Quân đội Hoa Kỳ hay Các lực lượng vũ trang Hoa...
3      Ngọc Lan ( 28 tháng 12 năm 1956 - 6 tháng 3 20...
4      Cô được coi là một trong những ca sĩ thuộc thế...
                             ...                        
495    Sóc Trăng là một tỉnh ven biển thuộc đồng bằng...
496    Đây là những điều cơ bản tiên quyết của cơ học...
497    Biến đổi khí hậu là những biến đổi trong môi t...
498    Phanxicô Xaviê Trương Bửu Diệp ( 1 tháng 1 năm...
499    Vùng trung du miền núi phía bắc , trước năm 19...
Name: text, Length: 500, dtype: str

In [169]:
#Convert to Lower
context = data['text']
context = [doc.lower() for doc in context]
context[:5]

['năm 2013 , nguyễn quang hải giành chức vô địch u21 quốc gia 2013 cùng với đội trẻ hà nội t&t và tạo nên cú sốc khi trở thành cầu thủ 16 tuổi đầu tiên giành được danh hiệu vô địch u21 quốc gia .',
 'một trận đấu bóng đá thông thường có hai hiệp , mỗi hiệp 45 phút với khoảng thời gian 15 phút nghỉ giữa hai hiệp .',
 'quân đội hoa kỳ hay các lực lượng vũ trang hoa kỳ là tổng hợp các lực lượng quân sự thống nhất của hoa kỳ . các lực lượng này gồm có lục quân , hải quân , thuỷ quân lục chiến , không quân và tuần duyên .',
 'ngọc lan ( 28 tháng 12 năm 1956 - 6 tháng 3 2001 ) là một ca sĩ hải ngoại nổi tiếng . không chỉ với giọng hát , cô còn được khán giả đặc biệt yêu mến vì khuôn mặt khả ái và tính cách nhút nhát , khiêm tốn của mình .',
 'cô được coi là một trong những ca sĩ thuộc thế hệ thứ hai của nền nhạc nhẹ việt nam đạt được nhiều giải thưởng nhất .']

In [170]:
tf_idf_vectorizer = TfidfVectorizer(max_features=500)

In [171]:
context_embeded = tf_idf_vectorizer.fit_transform(context)

In [172]:
context_embeded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16098 stored elements and shape (500, 500)>

In [173]:
tf_idf_vectorizer.vocabulary_

{'năm': np.int64(266),
 'nguyễn': np.int64(235),
 'hải': np.int64(151),
 'chức': np.int64(68),
 'vô': np.int64(427),
 'quốc': np.int64(299),
 'gia': np.int64(110),
 'cùng': np.int64(82),
 'với': np.int64(438),
 'đội': np.int64(491),
 'hà': np.int64(142),
 'nội': np.int64(272),
 'và': np.int64(424),
 'tạo': np.int64(399),
 'nên': np.int64(263),
 'khi': np.int64(163),
 'trở': np.int64(382),
 'thành': np.int64(334),
 'cầu': np.int64(88),
 'thủ': np.int64(351),
 'tuổi': np.int64(386),
 'đầu': np.int64(477),
 'tiên': np.int64(355),
 'được': np.int64(470),
 'danh': np.int64(94),
 'hiệu': np.int64(131),
 'một': np.int64(222),
 'trận': np.int64(379),
 'đấu': np.int64(476),
 'bóng': np.int64(37),
 'đá': np.int64(459),
 'thông': np.int64(339),
 'thường': np.int64(341),
 'có': np.int64(79),
 'hai': np.int64(127),
 'hiệp': np.int64(130),
 'khoảng': np.int64(166),
 'thời': np.int64(350),
 'gian': np.int64(112),
 '15': np.int64(6),
 'giữa': np.int64(121),
 'quân': np.int64(296),
 'hoa': np.int64(132

In [174]:
question = data.iloc[0]['question']
print(question)

Quang Hải giành được chức vô địch U21 quốc gia năm bao nhiêu tuổi


In [175]:
query_embeded = tf_idf_vectorizer.transform([question.lower()])
query_embeded.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.41170748, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.34409734, 0.        ,
        0.        , 0.        , 0.        , 0.  

In [176]:
from sklearn.metrics.pairwise import cosine_similarity
consine_scores = cosine_similarity(context_embeded, query_embeded).reshape((-1, ))

consine_scores

array([0.57893894, 0.        , 0.04324174, 0.11867385, 0.0462411 ,
       0.04020499, 0.09262766, 0.07334046, 0.        , 0.10025643,
       0.09711281, 0.10404656, 0.        , 0.11062764, 0.04483115,
       0.08200432, 0.08717163, 0.01513549, 0.02218694, 0.03012534,
       0.        , 0.01060537, 0.01596474, 0.04271932, 0.10404656,
       0.        , 0.07060081, 0.11980622, 0.        , 0.        ,
       0.12800329, 0.01610309, 0.        , 0.05859667, 0.05674335,
       0.        , 0.06027257, 0.07105423, 0.0127644 , 0.0246541 ,
       0.03086477, 0.02730909, 0.07375455, 0.01632256, 0.03539357,
       0.        , 0.05381381, 0.        , 0.03653642, 0.        ,
       0.10216567, 0.08786483, 0.        , 0.03455317, 0.        ,
       0.12924531, 0.02803859, 0.        , 0.03653642, 0.07474625,
       0.07644765, 0.04365014, 0.01421474, 0.        , 0.09518449,
       0.07664112, 0.03549977, 0.10371288, 0.        , 0.        ,
       0.07664112, 0.02238682, 0.03455317, 0.06027257, 0.08608

In [177]:
top_d = 5
for idx in consine_scores.argsort()[-top_d:][::-1]:
    print('Score: ',consine_scores[idx])
    print(data.iloc[idx, 2])
    print('______')


Score:  0.5789389362010777
Năm 2013 , Nguyễn Quang Hải giành chức vô địch U21 quốc gia 2013 cùng với đội trẻ Hà Nội T&T và tạo nên cú sốc khi trở thành cầu thủ 16 tuổi đầu tiên giành được danh hiệu vô địch U21 quốc gia .
______
Score:  0.37748766531906297
Bao Công huý là Bao Chửng ( chữ Hán : 包拯 ; 11 tháng 4 năm 999 - 20 tháng 5 năm 1062 ) , tự Hy Nhân . Ngoài ra , ông còn được gọi là Bao Thanh thiên , Bao Đãi chế , Bao Hắc tử , Bao Học sĩ hay Bao Long Đồ .
______
Score:  0.24329470996695696
Khi còn bé , Luffy đã vô tình ăn phải trái ác quỷ do Shanks dành dược từ thuyền địch nên anh đã trở thành người cao su . Tuy ăn phải trái ác quỷ làm cậu không thể bơi , nhưng mong muốn ra biển đặc biệt là ước muốn trở thành Vua Hải tặc và tìm được kho báu One Piece của Luffy vẫn không hề giảm . 10 năm sau từ quê hương là làng Foosha , ở Đảo Dawn thuộc East Blue , Luffy lên dường tìm kiếm đồng đội để lập băng hải tặc cho riêng mình , băng băng Mũ Rơm , hành trình trở thành Hải tặc của Luffy bắt đầu 

In [ ]:
corr_coef_scores = np.corrcoef(query_embeded.toarray()[0], context_embeded.toarray())
for index in corr_coef_scores[0][1:].argsort()[-top_d:][::-1]:
    print("Scores", corr_coef_scores[0][index])
    print(data.iloc[index, 2])
    print("_______________")


Scores 1.0


KeyError: (np.int64(0), 2)